# Generated by Django 4.2 on 2025-08-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=255)),
                ("long_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherModelRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reftime", models.DateTimeField()),
                (
                    "weather_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meteotiles.weathermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherProductRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=255)),
                ("long_name", models.CharField(max_length=255)),
                ("forecast_steps", models.JSONField()),
                ("lat_min", models.FloatField()),
                ("lon_min", models.FloatField()),
                ("lat_max", models.FloatField()),
                ("lon_max", models.FloatField()),
                ("min_zoom", models.IntegerField()),
                ("max_zoom", models.IntegerField()),
                ("zindex", models.IntegerField()),
                ("opacity", models.FloatField()),
                ("legend_on", models.BooleanField()),
                (
                    "weather_model_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meteotiles.weathermodelrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="weathermodel",
            constraint=models.UniqueConstraint(
                fields=("short_name",), name="unique_short_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="weatherproductrun",
            constraint=models.UniqueConstraint(
                fields=("weather_model_run", "short_name"),
                name="unique_weather_model_run_short_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="weathermodelrun",
            constraint=models.UniqueConstraint(
                fields=("weather_model", "reftime"),
                name="unique_weather_models_reftime",
            ),
        ),
    ]
