# Generated by Django 4.2 on 2025-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteotiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherproductrun",
            name="opacity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weatherproductrun",
            name="zindex",
            field=models.IntegerField(null=True),
        ),
    ]
