# Generated by Django 4.2 on 2025-09-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meteotiles", "0002_alter_weatherproductrun_opacity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherproductrun",
            old_name="max_zoom",
            new_name="zoom_max",
        ),
        migrations.RenameField(
            model_name="weatherproductrun",
            old_name="min_zoom",
            new_name="zoom_min",
        ),
    ]
