# Generated by Django 4.2 on 2025-10-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("meteotiles", "0003_rename_max_zoom_weatherproductrun_zoom_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathermodel",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True, related_name="weather_models", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="weathermodel",
            name="public",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
